version: 2.1
jobs:

    build_and_push_to_pypi:
        docker:
            - image: circleci/python:3.6.4
        steps:
            - checkout

            - run:
                name: Install the dependencies
                command: python3 -m pip install --user --upgrade setuptools wheel twine

            - run:
                name: Build the package
                command: python3 setup.py sdist bdist_wheel
            
            - run:
                name: Push to PyPi
                command: python3 -m twine upload -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD} --repository-url https://upload.pypi.org/legacy/ dist/*


workflows:
  version: 2
  workflow:
    jobs:
        # Run this job only for release
        - build_and_push_to_pypi:
            filters:
                branches:
                    ignore: /.*/
                tags:
                    only: /^[0-9]+.[0-9]+.[0-9]+$/
